const http=require('http');
const fs=require('fs');
const path=require('path');
const crypto=require('crypto');
const PORT=Number(process.env.PORT)||8787;
const ROOT=__dirname;
const rooms=new Map();
const ROOM_TTL=24*60*60*1000;
const DATA_FILE=path.join(ROOT,'friends.json');
let friendDb={profiles:{},friends:{}};
try{if(fs.existsSync(DATA_FILE))friendDb=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch{friendDb={profiles:{},friends:{}}}
function saveFriends(){try{const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(friendDb,null,2));fs.renameSync(tmp,DATA_FILE)}catch{}}
function cleanFriendId(v){return String(v||'').trim().toUpperCase().replace(/[^A-Z0-9-]/g,'').slice(0,20)}
const MAX_BODY=1024*1024;
function headers(type='application/json; charset=utf-8'){return {'Content-Type':type,'Cache-Control':'no-store','Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,OPTIONS'}}
function json(res,status,obj){res.writeHead(status,headers());res.end(JSON.stringify(obj))}
function text(res,status,s,type='text/plain; charset=utf-8'){res.writeHead(status,headers(type));res.end(s)}
function parseBody(req){return new Promise((resolve,reject)=>{let s='';req.on('data',c=>{s+=c;if(s.length>MAX_BODY){reject(new Error('Body too large'));req.destroy()}});req.on('end',()=>{if(!s)return resolve({});try{resolve(JSON.parse(s))}catch(e){reject(new Error('Invalid JSON'))}});req.on('error',reject)})}
function makeCode(){let c;do c=crypto.randomBytes(3).toString('hex').toUpperCase();while(rooms.has(c));return c}
function playerId(){return crypto.randomUUID()}
function cleanName(v,f){const s=String(v??'').trim().replace(/[\r\n\t]/g,' ');return (s||f).slice(0,40)}
function publicRoom(r){return {code:r.code,players:r.players.map(p=>({id:p.id,name:p.name,profile:p.profile})),ready:r.players.length===2,createdAt:r.createdAt}}
function freshRoomState(){return {started:false,mode:'campana',intensityCap:20,level:1,round:0,position:0,turn:'A',answers:{},scores:{A:0,B:0},streak:0,bestStreak:0,bonus:1,items:{joker:2,shield:1,reroll:1,heart:1},unlocked:[],achievements:[],messages:[],rolls:0,skips:0,gems:0,completedLevels:[],effects:{},specialCount:{},levelProgress:0,bossesDone:[],finalChoice:null,history:[]}}
function getRoom(code){return rooms.get(String(code||'').toUpperCase())}
function serveStatic(req,res,pathname){let rel=pathname==='/'?'/index.html':pathname;rel=decodeURIComponent(rel);if(rel.includes('..'))return text(res,400,'Bad path');const fp=path.join(ROOT,rel);if(!fs.existsSync(fp)||!fs.statSync(fp).isFile())return text(res,404,'Not found');const ext=path.extname(fp).toLowerCase();const types={'.html':'text/html; charset=utf-8','.js':'application/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.svg':'image/svg+xml','.webp':'image/webp','.ico':'image/x-icon','.webmanifest':'application/manifest+json'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','Cache-Control':ext==='.html'?'no-cache':'public, max-age=3600'});fs.createReadStream(fp).pipe(res)}
function routeCode(pathname){const m=pathname.match(/^\/api\/(?:room|rooms)\/([^/]+)/);return m?decodeURIComponent(m[1]).toUpperCase():null}
const server=http.createServer(async(req,res)=>{try{
 if(req.method==='OPTIONS'){res.writeHead(204,headers());return res.end()}
 const url=new URL(req.url,'http://localhost');const p=url.pathname;
 if(req.method==='GET'&&(p==='/'||p==='/index.html'||p==='/cards.json'||p.endsWith('.js')||p.endsWith('.css')||p.endsWith('.png')||p.endsWith('.jpg')||p.endsWith('.jpeg')||p.endsWith('.svg')||p.endsWith('.webp')||p.endsWith('.ico')||p.endsWith('.json')||p.endsWith('.webmanifest')))return serveStatic(req,res,p);
 if(req.method==='POST'&&p==='/api/profile/register'){const b=await parseBody(req);const id=cleanFriendId(b.id)||('SE-'+crypto.randomBytes(4).toString('hex').toUpperCase());const name=cleanName(b.name,'Jugador');friendDb.profiles[id]={id,name,updatedAt:Date.now()};friendDb.friends[id]=friendDb.friends[id]||[];saveFriends();return json(res,200,{ok:true,profile:friendDb.profiles[id],friends:friendDb.friends[id].map(x=>friendDb.profiles[x]).filter(Boolean)})}
 if(req.method==='GET'&&p.startsWith('/api/friends/')){const id=cleanFriendId(p.slice('/api/friends/'.length));if(!id)return json(res,400,{ok:false,error:'Falta el perfil.'});const f=friendDb.friends[id]||[];return json(res,200,{ok:true,profile:friendDb.profiles[id]||null,friends:f.map(x=>friendDb.profiles[x]).filter(Boolean)})}
 if(req.method==='POST'&&p==='/api/friends/add'){const b=await parseBody(req);const id=cleanFriendId(b.id),fid=cleanFriendId(b.friendCode);if(!id||!fid)return json(res,400,{ok:false,error:'Falta el código de amigo.'});if(!friendDb.profiles[id])friendDb.profiles[id]={id,name:'Jugador',updatedAt:Date.now()};if(!friendDb.profiles[fid])return json(res,404,{ok:false,error:'No existe ese código de amigo.'});friendDb.friends[id]=friendDb.friends[id]||[];friendDb.friends[fid]=friendDb.friends[fid]||[];if(!friendDb.friends[id].includes(fid))friendDb.friends[id].push(fid);if(!friendDb.friends[fid].includes(id))friendDb.friends[fid].push(id);saveFriends();return json(res,200,{ok:true,friend:friendDb.profiles[fid]})}
 if(req.method==='GET'&&(p==='/health'||p==='/api/health'))return json(res,200,{ok:true,status:'online',service:'sin-escapatoria',port:PORT,rooms:rooms.size});
 if(req.method==='POST'&&['/api/create-room','/api/create','/api/rooms'].includes(p)){const b=await parseBody(req);const player={id:playerId(),name:cleanName(b.name||b.player||b.profile,'Jugador 1'),profile:b.profile==='B'?'B':'A'};const code=makeCode();const r={code,players:[player],createdAt:Date.now(),state:{},messages:[]};rooms.set(code,r);return json(res,201,{ok:true,success:true,code,roomCode:code,room:publicRoom(r),player})}
 if(req.method==='POST'&&['/api/join-room','/api/join','/api/rooms/join'].includes(p)){const b=await parseBody(req);const code=String(b.code||b.roomCode||b.room||b.codigo||'').trim().toUpperCase();if(!code)return json(res,400,{ok:false,error:'Falta el código de la sala.'});const r=getRoom(code);if(!r)return json(res,404,{ok:false,error:'La sala no existe o ha caducado.'});if(r.players.length>=2)return json(res,409,{ok:false,error:'La sala ya tiene dos jugadores.'});const used=r.players.map(x=>x.profile);let profile=b.profile==='A'||b.profile==='B'?b.profile:(used.includes('A')?'B':'A');if(used.includes(profile))profile=profile==='A'?'B':'A';const player={id:playerId(),name:cleanName(b.name||b.player||b.profile,'Jugador 2'),profile};r.players.push(player);if(!r.state||!Object.keys(r.state).length)r.state=freshRoomState();return json(res,200,{ok:true,success:true,code,roomCode:code,room:publicRoom(r),player,state:r.state})}
 const code=routeCode(p);
 if(req.method==='GET'&&code&&!p.endsWith('/state')){const r=getRoom(code);if(!r)return json(res,404,{ok:false,error:'La sala no existe o ha caducado.'});if(!r.state||!Object.keys(r.state).length)r.state=freshRoomState();return json(res,200,{ok:true,success:true,room:publicRoom(r),state:r.state})}
 if(req.method==='POST'&&code&&p.endsWith('/state')){const r=getRoom(code);if(!r)return json(res,404,{ok:false,error:'Sala no encontrada.'});const b=await parseBody(req);r.state=b.state!==undefined?b.state:b;return json(res,200,{ok:true,success:true,state:r.state})}
 if(req.method==='POST'&&code&&p.endsWith('/state/answer')){const r=getRoom(code);if(!r)return json(res,404,{ok:false,error:'Sala no encontrada.'});const b=await parseBody(req);const s=r.state&&Object.keys(r.state).length?r.state:freshRoomState();const profile=b.profile==='B'?'B':'A';const round=Number(b.round??s.round??0);if(round!==Number(s.round||0))return json(res,409,{ok:false,error:'Ronda desactualizada.',state:s});s.answers={...(s.answers||{}),[profile]:{round,value:b.value}};r.state=s;const a=s.answers?.A,c=s.answers?.B;const resolved=a?.round===round&&c?.round===round;return json(res,200,{ok:true,resolved,state:s})}
 if(req.method==='POST'&&code&&p.endsWith('/state/resolve')){const r=getRoom(code);if(!r)return json(res,404,{ok:false,error:'Sala no encontrada.'});const b=await parseBody(req);const s=r.state&&Object.keys(r.state).length?r.state:freshRoomState();const round=Number(b.round??s.round??0);if(Number(s.round||0)!==round)return json(res,409,{ok:false,error:'La ronda ya fue resuelta.',state:s});const a=s.answers?.A,c=s.answers?.B;if(a?.round!==round||c?.round!==round)return json(res,409,{ok:false,error:'Faltan respuestas.',state:s});if(s.resolvingRound===round)return json(res,200,{ok:true,state:s});s.resolvingRound=round;const match=String(a.value)!=='done'&&String(c.value)!=='done'&&String(a.value)===String(c.value);const streak=match?Number(s.streak||0)+1:0;const best=Math.max(Number(s.bestStreak||0),streak);const bonus=match?Math.min(5,Number(s.bonus||1)+1):Math.max(1,Number(s.bonus||1)-1);const scores={A:Number(s.scores?.A||0),B:Number(s.scores?.B||0)};if(match){scores.A+=Number(b.pointsA||1);scores.B+=Number(b.pointsB||1)}else{scores.A+=Number(b.pointsA||0);scores.B+=Number(b.pointsB||0)}const pos=Math.min(39,Number(s.position||0)+1+(match?1:0));const progress=Number(s.levelProgress||0)+1;const achievements=[...(s.achievements||[])];if(match&&!achievements.includes('🤝 Primera coincidencia'))achievements.push('🤝 Primera coincidencia');if(streak>=3&&!achievements.includes('🔥 Racha x3'))achievements.push('🔥 Racha x3');if(streak>=5&&!achievements.includes('🔥 Racha x5'))achievements.push('🔥 Racha x5');const gems=Number(s.gems||0)+(pos>0&&pos%7===0?1:0);r.state={...s,round:round+1,position:pos,turn:profileOther(s.turn),answers:{},streak,bestStreak:best,bonus,scores,levelProgress:progress,gems,resolvingRound:null,history:[...(s.history||[]),{round,match,level:s.level,pos}]};return json(res,200,{ok:true,resolved:true,match,state:r.state})}
 if(req.method==='POST'&&code&&p.endsWith('/message')){const r=getRoom(code);if(!r)return json(res,404,{ok:false,error:'Sala no encontrada.'});const b=await parseBody(req);const m={id:playerId(),from:String(b.from||b.player||''),text:String(b.text||b.message||'').replace(/[\r\n]/g,' ').slice(0,500),at:Date.now()};r.messages=(r.messages||[]).concat(m).slice(-100);r.state=r.state||freshRoomState();r.state.messages=r.messages;return json(res,200,{ok:true,message:m,state:r.state})}
 return text(res,404,'Not found');
}catch(e){return json(res,400,{ok:false,error:e.message||'Error'})}});
function profileOther(p){return p==='A'?'B':'A'}
setInterval(()=>{const now=Date.now();for(const [code,r] of rooms){if(now-r.createdAt>ROOM_TTL)rooms.delete(code)}},60*60*1000).unref();
server.listen(PORT,()=>console.log('Sin Escapatoria · V11 5D en http://localhost:'+PORT));
